[2025-10-19T16:18:12.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-19T16:18:12.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_data_pipeline.extract scheduled__2025-10-18T06:00:00+00:00 [queued]>
[2025-10-19T16:18:12.252+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_data_pipeline.extract scheduled__2025-10-18T06:00:00+00:00 [queued]>
[2025-10-19T16:18:12.253+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-19T16:18:12.267+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract> on 2025-10-18 06:00:00+00:00
[2025-10-19T16:18:12.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbnb_data_pipeline', 'extract', 'scheduled__2025-10-18T06:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_pipeline_dag.py', '--cfg-path', '/tmp/tmp4qs4ao05']
[2025-10-19T16:18:12.277+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract
[2025-10-19T16:18:12.276+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-19T16:18:12.278+0000] {standard_task_runner.py:63} INFO - Started process 260 to run task
[2025-10-19T16:18:12.344+0000] {task_command.py:426} INFO - Running <TaskInstance: airbnb_data_pipeline.extract scheduled__2025-10-18T06:00:00+00:00 [running]> on host 89568661f918
[2025-10-19T16:18:12.430+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbnb_data_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-18T06:00:00+00:00'
[2025-10-19T16:18:12.431+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-19T16:18:12.444+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T16:18:12.446+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/extract.py']
[2025-10-19T16:18:12.454+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T16:18:12.924+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T16:18:12.925+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/extract.py", line 8, in <module>
[2025-10-19T16:18:12.928+0000] {subprocess.py:93} INFO -     RAW_DIR.mkdir(parents=True, exist_ok=True)
[2025-10-19T16:18:12.929+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
[2025-10-19T16:18:12.929+0000] {subprocess.py:93} INFO -     os.mkdir(self, mode)
[2025-10-19T16:18:12.930+0000] {subprocess.py:93} INFO - FileExistsError: [Errno 17] File exists: '/opt/***/data/raw'
[2025-10-19T16:18:12.948+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T16:18:12.949+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-19T16:18:12.962+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T16:18:12.967+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=airbnb_data_pipeline, task_id=extract, run_id=scheduled__2025-10-18T06:00:00+00:00, execution_date=20251018T060000, start_date=20251019T161812, end_date=20251019T161812
[2025-10-19T16:18:12.982+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 260)
[2025-10-19T16:18:13.017+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-19T16:18:13.040+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-19T16:18:13.045+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
