[2025-10-19T16:13:10.188+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-19T16:13:10.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_data_pipeline.extract scheduled__2025-10-18T06:00:00+00:00 [queued]>
[2025-10-19T16:13:10.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_data_pipeline.extract scheduled__2025-10-18T06:00:00+00:00 [queued]>
[2025-10-19T16:13:10.233+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-19T16:13:10.246+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract> on 2025-10-18 06:00:00+00:00
[2025-10-19T16:13:10.252+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbnb_data_pipeline', 'extract', 'scheduled__2025-10-18T06:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_pipeline_dag.py', '--cfg-path', '/tmp/tmpu118cdjh']
[2025-10-19T16:13:10.255+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask extract
[2025-10-19T16:13:10.255+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=206) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-19T16:13:10.256+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-10-19T16:13:10.330+0000] {task_command.py:426} INFO - Running <TaskInstance: airbnb_data_pipeline.extract scheduled__2025-10-18T06:00:00+00:00 [running]> on host 89568661f918
[2025-10-19T16:13:10.436+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbnb_data_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-18T06:00:00+00:00'
[2025-10-19T16:13:10.438+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-19T16:13:10.471+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T16:13:10.473+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/extract.py']
[2025-10-19T16:13:10.482+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T16:13:10.972+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T16:13:10.972+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/extract.py", line 8, in <module>
[2025-10-19T16:13:10.975+0000] {subprocess.py:93} INFO -     RAW_DIR.mkdir(parents=True, exist_ok=True)
[2025-10-19T16:13:10.975+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
[2025-10-19T16:13:10.976+0000] {subprocess.py:93} INFO -     os.mkdir(self, mode)
[2025-10-19T16:13:10.976+0000] {subprocess.py:93} INFO - FileExistsError: [Errno 17] File exists: '/opt/***/data/raw'
[2025-10-19T16:13:10.993+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T16:13:10.994+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-19T16:13:11.006+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T16:13:11.013+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=airbnb_data_pipeline, task_id=extract, run_id=scheduled__2025-10-18T06:00:00+00:00, execution_date=20251018T060000, start_date=20251019T161310, end_date=20251019T161311
[2025-10-19T16:13:11.027+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 207)
[2025-10-19T16:13:11.075+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-19T16:13:11.096+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-19T16:13:11.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
